
dist: trusty

language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - node_modules

script:
  - npm run build && npm run export
  - npm install now -g
  - now ./public -t $NOW_TOKEN -A ../now.json && now alias -t $NOW_TOKEN