
dist: trusty

language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - node_modules

before_deploy: npm install now -g

script:
  - npm run build
  - now public --token $NOW_TOKEN && now alias --token $NOW_TOKEN